---

- name: thinkpad
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_prompt:
    - name: username
      prompt: What is your username?
      private: no
    - name: ansible_become_password
      prompt: Enter sudo password
      private: yes
  tasks:
    - name: configure pacman & update
      include_tasks: tasks/pacman.yml
    - name: install core packages
      include_tasks: tasks/core.yml
    - name: turn capslock into second esc key
      include_tasks: tasks/keyboard.yml
    - name: install fonts 
      include_tasks: tasks/fonts.yml
    - name: install & configure zsh
      include_tasks: tasks/zsh.yml
    - name: install & ghostty terminal emulator
      include_tasks: tasks/ghostty.yml
    - name: install & configure i3
      include_tasks: tasks/i3.yml
    - name: install & configure tmux 
      include_tasks: tasks/tmux.yml
    - name: install dev tools
      include_tasks: tasks/dev.yml
    - name: configure neovim 
      include_tasks: tasks/nvim.yml
    - name: automate usb mounting
      include_tasks: tasks/usb.yml
