---

- name: Create personal cheatsheets directory
  ansible.builtin.file:
    path: "/home/{{ username }}/.config/cheat/cheatsheets/personal"
    state: directory
    mode: '0755'

- name: Clone community cheatsheets repository
  ansible.builtin.git:
    repo: git@github.com:cheat/cheatsheets.git
    dest: "/home/{{ username }}/.config/cheat/cheatsheets/community"
    accept_hostkey: yes

- name: Get stats on cheat config
  ansible.builtin.stat:
    path: /home/{{ username }}/.config/cheat/conf.yml
  register: c

- name: Get stats on cheat config
  ansible.builtin.stat:
    path: /home/{{ username }}/.config/cheat/cheatsheets/personal
  register: p

- name: check for cheat config that is not a symlink
  become: yes
  ansible.builtin.file:
    path: /home/{{ username }}/.config/cheat/conf.yml
    state: absent
  when: c.stat.isreg is defined and c.stat.isreg

- name: check for cheat config that is not a symlink
  become: yes
  ansible.builtin.file:
    path: /home/{{ username }}/.config/cheat/cheatsheets/personal
    state: absent
  when: p.stat.isdir is defined and p.stat.isdir

- name: unlink any cheat config if symlink
  become: yes
  file:
    path: /home/{{ username }}/.config/cheat/conf.yml
    state: absent
  when: c.stat.exists and c.stat.islnk

- name: unlink any cheat config if symlink
  become: yes
  file:
    path: /home/{{ username }}/.config/cheat/cheatsheets/personal
    state: absent
  when: c.stat.exists and c.stat.islnk

- name: create a new symlink from repo config
  become: yes
  ansible.builtin.file:
    src: "{{ playbook_dir }}/dotfiles/cheatsheets/conf.yml"
    dest: /home/{{ username }}/.config/cheat/conf.yml
    state: link

- name: create a new symlink from repo config
  become: yes
  ansible.builtin.file:
    src: "{{ playbook_dir }}/dotfiles/cheatsheets/personal"
    dest: /home/{{ username }}/.config/cheat/cheatsheets/personal
    state: link
