- name: Install language tools available in community packages
  become: true
  community.general.pacman:
    name:
      - i3
      - i3status
      - dmenu
    state: present

- name: Get stat of i3 config
  ansible.builtin.stat:
    path: /home/{{ username }}/.config/i3
  register: i3_stat

- name: Remove any i3 config that is not a symlink
  ansible.builtin.file:
    path: /home/{{ username }}/.config/i3
    state: absent
  when: i3_stat.stat.isdir is defined and i3_stat.stat.isdir

- name: Unlink i3 config if it's a symlink
  file:
    path: /home/{{ username }}/.config/i3
    state: absent
  when: i3_stat.stat.exists and i3_stat.stat.islnk

- name: Creating a symlink to i3 config
  ansible.builtin.file:
    src: "{{ playbook_dir }}/dotfiles/i3/.config/i3"
    dest: /home/{{ username }}/.config/i3
    state: link

- name: Get stat of i3status
  ansible.builtin.stat:
    path: /home/{{ username }}/.config/i3status
  register: i3status_stat

- name: Remove any i3status config that is not a symlink
  ansible.builtin.file:
    path: /home/{{ username }}/.config/i3status
    state: absent
  when: i3status_stat.stat.isdir is defined and i3status_stat.stat.isdir

- name: Unlink i3status config if it's a symlink
  file:
    path: /home/{{ username }}/.config/i3status
    state: absent
  when: i3status_stat.stat.exists and i3status_stat.stat.islnk

- name: Creating a symlink from i3status config
  ansible.builtin.file:
    src: "{{ playbook_dir }}/dotfiles/i3/.config/i3status"
    dest: /home/{{ username }}/.config/i3status
    state: link
