---

- name: Set up my Neovim config
  block:
    - name: Update nvimconf submodule
      git:
        update: yes
        repo: "git@github.com:ge3224/nvimconf.git"
        dest: "{{ playbook_dir }}/dotfiles/nvim"
        track_submodules: yes

    - name: Create Neovim config symlink
      file:
        src: "{{ playbook_dir }}/dotfiles/nvim"
        dest: "~/.config/nvim"
        state: link
        force: yes
      become: no
