---

- name: Install pandoc
  become: yes
  community.general.pacman:
    name:
      - pandoc
      - texlive-core
      - texlive-bin
      - texlive-latexextra
      - texlive-fontsrecommended
    state: present
