---

- name: Install CUPS printing system
  become: yes
  community.general.pacman:
    name:
      - cups
      - cups-pdf
      - system-config-printer
      - ghostscript
      - gsfonts
    state: present

- name: Install printer drivers (common manufacturers)
  become: yes
  community.general.pacman:
    name:
      - gutenprint
      - hplip
      - splix
    state: present

- name: Start and enable CUPS service
  become: yes
  ansible.builtin.systemd:
    name: cups.service
    state: started
    enabled: yes

- name: Add user to lp group for printer access
  become: yes
  ansible.builtin.user:
    name: "{{ username }}"
    groups: lp
    append: yes