---

- name: Check if directory is a git repository
  stat:
    path: "{{ playbook_dir }}/.git"
  register: git_status

- name: Fail if not a git repository
  fail:
    msg: "The specified directory {{ playbook_dir }} is not a git repository"
  when: not git_status.stat.exists

- name: Initialize git submodules
  command:
    cmd: git submodule init
    chdir: "{{ playbook_dir }}"
  register: init_result
  changed_when: init_result.stdout != ""
  failed_when: 
    - init_result.rc != 0
    - "'already initialized' not in init_result.stderr"

- name: Update git submodules
  command:
    cmd: git submodule update
    chdir: "{{ playbook_dir }}"
  register: update_result
  changed_when: update_result.stdout != ""

- name: Update submodules to latest remote version
  command:
    cmd: git submodule update --remote
    chdir: "{{ playbook_dir }}"
  register: remote_update_result
  changed_when: remote_update_result.stdout != ""
  when: force_update | bool
