---

- name: Install 'throttled' package for T480
  become: yes
  community.general.pacman:
    name:
      - throttled

- name: Start & enable 'throttled' service
  become: yes
  ansible.builtin.systemd:
    name: throttled
    state: started
    enabled: true

- name: Install 'msr-tools' package fro T480
  become: yes
  community.general.pacman:
    name:
      - msr-tools

- name: Install msr-tools package
  become: yes
  community.general.pacman:
    name:
      - msr-tools

- name: Create throttlestop script
  become: yes
  ansible.builtin.copy:
    dest: /usr/local/bin/throttlestop
    mode: '0755'
    content: |
      #!/bin/bash
      modprobe msr
      reg="$(rdmsr -d 0x1FC)"
      if [ $((reg%2)) -eq 1 ]; then
          wrmsr 0x1FC $((reg-1))
      fi

- name: Create throttlestop service
  become: yes
  ansible.builtin.copy:
    dest: /etc/systemd/system/throttlestop.service
    mode: '0644'
    content: |
      [Unit]
      Description=Disable BD PROCHOT throttling
      After=multi-user.target

      [Service]
      Type=oneshot
      ExecStart=/usr/local/bin/throttlestop
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target

- name: Start & enable throttlestop service
  become: yes
  ansible.builtin.systemd:
    name: throttlestop
    state: started
    enabled: true

- name: Install 'fwupd' for firmware updates
  become: yes
  community.general.pacman:
    name:
      - fwupd

- name: Remove xorg-xbacklight if installed
  become: yes
  pacman:
    name: xorg-xbacklight
    state: absent

- name: Install acpilight
  become: yes
  pacman:
    name: acpilight
    state: present

- name: Add user to video group
  become: yes
  user:
    name: "{{ username }}"
    groups: video
    append: yes

- name: Create udev rules for backlight control
  become: yes
  copy:
    dest: /etc/udev/rules.d/90-backlight.rules
    mode: '0644'
    content: |
      SUBSYSTEM=="backlight", ACTION=="add", \
        RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness", \
        RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"

      SUBSYSTEM=="leds", ACTION=="add", KERNEL=="*::kbd_backlight", \
        RUN+="/bin/chgrp video /sys/class/leds/%k/brightness", \
        RUN+="/bin/chmod g+w /sys/class/leds/%k/brightness"

- name: Reload udev rules
  become: yes
  command: udevadm control --reload-rules

- name: Trigger udev rules
  become: yes
  command: udevadm trigger
