---

- name: Install tmux if missing
  become: yes
  community.general.pacman:
    name:
      - tmux
    state: present

- name: Get stat on tmux config
  ansible.builtin.stat:
    path: /home/{{ username }}/.tmux.conf
  register: tmux_stat

- name: Remove any tmux config that is not a symlink
  ansible.builtin.file:
    path: /home/{{ username }}/.tmux.conf
    state: absent
  when: tmux_stat.stat.isdir is defined and tmux_stat.stat.isdir

- name: Unlink tmux config if it's a symlink
  file:
    path: /home/{{ username }}/.tmux.conf
    state: absent
  when: tmux_stat.stat.exists and tmux_stat.stat.islnk

- name: Create a symlink to tmux config in repo
  ansible.builtin.file:
    src: "{{ playbook_dir }}/dotfiles/tmux/.tmux.conf"
    dest: /home/{{ username }}/.tmux.conf
    state: link
