---

- name: Install z-shell package if not present
  community.general.pacman:
    name: 
      - zsh
    state: present
  become: true

- name: Set zsh as default shell
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh
  become: true

- name: Check if .zshrc exists
  stat:
    path: /home/{{ username }}/.zshrc
  register: zshrc_stat

- name: Remove .zshrc if it exists and is not a symlink
  file:
    path: /home/{{ username }}/.zshrc
    state: absent
  when: zshrc_stat.stat.exists and not zshrc_stat.stat.islnk

- name: Unlink .zshrc if it's a symlink
  file:
    path: /home/{{ username }}/.zshrc
    state: absent
  when: zshrc_stat.stat.exists and zshrc_stat.stat.islnk

- name: Create symlink for .zshrc
  file:
    src: "{{ playbook_dir }}/dotfiles/zsh/.zshrc"
    dest: /home/{{ username }}/.zshrc
    state: link
